# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

barcodeMatch <- function(seq, barcodes, mu, sigma, sigma_start, k, batch, top, cos_thresh, alpha, edit_thresh, UMI_len, flank) {
    .Call(`_Longcellsrc_barcodeMatch`, seq, barcodes, mu, sigma, sigma_start, k, batch, top, cos_thresh, alpha, edit_thresh, UMI_len, flank)
}

NeighborExtract <- function(reads, id, pos, UMI_len, flank, bar_len) {
    .Call(`_Longcellsrc_NeighborExtract`, reads, id, pos, UMI_len, flank, bar_len)
}

isos2exonids_index <- function(isoform, start, end, exon_id, mid_bias, end_bias, end_overlap, nonsense_label, split, sep) {
    .Call(`_Longcellsrc_isos2exonids_index`, isoform, start, end, exon_id, mid_bias, end_bias, end_overlap, nonsense_label, split, sep)
}

extractReads <- function(seq, cigar, pos, annotation, strand, toolkit, end_flank, splice_site_bin) {
    .Call(`_Longcellsrc_extractReads`, seq, cigar, pos, annotation, strand, toolkit, end_flank, splice_site_bin)
}

cigarProcess <- function(cigar) {
    .Call(`_Longcellsrc_cigarProcess`, cigar)
}

seqEnd <- function(start, mark, count) {
    .Call(`_Longcellsrc_seqEnd`, start, mark, count)
}

isos_dis <- function(isoforms, thresh, split, sep) {
    .Call(`_Longcellsrc_isos_dis`, isoforms, thresh, split, sep)
}

size_filter_cpp <- function(size, ratio) {
    .Call(`_Longcellsrc_size_filter_cpp`, size, ratio)
}

splice_site_table_cpp <- function(isoform, split, sep, splice_site_thresh) {
    .Call(`_Longcellsrc_splice_site_table_cpp`, isoform, split, sep, splice_site_thresh)
}

#' extractTagFastq
NULL

#' extractTag
NULL

#' strSlideSearch
NULL

#' strSubset
NULL

#' polyADetect
NULL

#' polyARm
NULL

#' baseCount
NULL

#' reverseComplement
NULL

#' replicate
NULL

extractTagFastq <- function(fastq_path, out_path, adapter, toolkit, window, step, len, polyA_bin, polyA_base_count, polyA_len) {
    .Call(`_Longcellsrc_extractTagFastq`, fastq_path, out_path, adapter, toolkit, window, step, len, polyA_bin, polyA_base_count, polyA_len)
}

strSlideSearch <- function(seq, adapter, window, step, first) {
    .Call(`_Longcellsrc_strSlideSearch`, seq, adapter, window, step, first)
}

baseCount <- function(seq, base) {
    .Call(`_Longcellsrc_baseCount`, seq, base)
}

shareNeighbor <- function(index, neighbor, count) {
    .Call(`_Longcellsrc_shareNeighbor`, index, neighbor, count)
}

isoform2sites <- function(iso, split, sep) {
    .Call(`_Longcellsrc_isoform2sites`, iso, split, sep)
}

sites_chop <- function(sites, start, end) {
    .Call(`_Longcellsrc_sites_chop`, sites, start, end)
}

iso2_mid_dist <- function(a, b, split, sep) {
    .Call(`_Longcellsrc_iso2_mid_dist`, a, b, split, sep)
}

iso2_mid_diff <- function(a, b, end_bias, split, sep) {
    .Call(`_Longcellsrc_iso2_mid_diff`, a, b, end_bias, split, sep)
}

isoset_mid_diff <- function(iso_set1, iso_set2, thresh, overlap_thresh, end_bias, split, sep) {
    .Call(`_Longcellsrc_isoset_mid_diff`, iso_set1, iso_set2, thresh, overlap_thresh, end_bias, split, sep)
}

umi_graph_table <- function(umi, isoform, count, sim_thresh, iso_thresh, split, sep) {
    .Call(`_Longcellsrc_umi_graph_table`, umi, isoform, count, sim_thresh, iso_thresh, split, sep)
}

